baseURL = "https://www.wcnexus.com/venture/"
theme = "wcnexus-venture"

pygmentsCodeFences = true
pygmentsUseClasses = true

[Languages]
  [Languages.en]
  title = "wcnexus Venture"
  [Languages.zh]
  title = "wcnexus 冒险"

[params]
description = "Theme for wcnexus.com venture page"
img0 = "images/defaultPost.png" # the default fetured image for posts
weiboAPI = ""

  [[params.navs]]
  link = "/#index"
    [params.navs.title]
      en = "Index"
      zh = "首页"
  

  [[params.navs]]
  link = "/venture"
    [params.navs.title]
    en = "Venture"
    zh = "冒险"

  [params.user]
  name = "Valorad"
  fullName = "Valorad the Oneiroseeker"
  cover = "images/landscape.jpg"
  avatar = "images/fallout-VaultBoy-2.jpg" # the name of the file being used as the avatar, placed in "static" folder.
  intro = "This dude was too confused to make a bio."

  [params.social]
  weibo = ""
  zhihu = ""
  twitter = ""
  github = ""
  linkedin = ""
  facebook = ""
  instagram = ""
  youtube = ""