baseURL = "https://www.wcnexus.com/venture/"
languageCode = "en-us"
title = "wcnexus"
theme = "wcnexus-venture"

pygmentsCodeFences = true
pygmentsUseClasses = true

[params]

description = "Theme for wcnexus.com venture page"
img0 = "images/defaultPost.png" # the default fetured image for posts
weiboAPI = ""

  [[params.navs]]
  title = "Index"
  link = "/#index"

  [[params.navs]]
  title = "Venture"
  link = "/venture"

  [params.user]
  name = "Valorad"
  fullName = "Valorad the Oneiroseeker"
  cover = "images/landscape.jpg"
  avatar = "images/fallout-VaultBoy-2.jpg" # the name of the file being used as the avatar, placed in "static" folder.
  intro = "This dude was too confused to make a bio."

  [params.social]
  weibo = ""
  zhihu = ""
  twitter = ""
  github = ""
  linkedin = ""
  facebook = ""
  instagram = ""
  youtube = ""